= Hello-Study-World

사용자 추천 기반 학습 컨텐츠 제공 시스템 'Hello-Study-World'입니다.

== 프로젝트 목표

> ***이 소프트웨어는 세상에 어떤 가치를 줄 수 있나요?***

우리에게 지금 당장 필요한 것이 무엇인지 고민했고, 결론은 **학습과 이를 통한 성장**이었습니다. 여러 요소들이 필요했지만 소프트웨어로 빠르게 제공 가능한 요소는 양질의 학습 자료였습니다. 
  
정보의 홍수에서 질 좋은 학습 자료를 발견하는게 쉽지 않았습니다. 학습할 시간도 없는데 자료를 찾는데에 시간을 투여하는 것이 '학습의 오버헤드'라고 느꼈습니다.
  
같은 고민을 하는 개발자들이 힘을 합쳐 **서로에게 도움을 주는 공간**을 만들고 싶었습니다. 개발자 특유의 공유 문화를 활용해 먼저 걸어갔던 누군가가 **무엇이, 왜 좋은지**를 알려주면 좋지 않을까? 생각했습니다. 그래서 저희는 양질의 자료와 그 이유까지 빠르게 얻어가는 시스템을 만들기로 했습니다.			


== 기술적 고민

> *프로젝트를 진행하며 고민했던 요소와 왜 선택하게 됐는지?*

- *테스트를 Small, Medium, Large로 나눈 이유는 무엇인가요?*

Spring Boot에서 제공하는 슬라이스 테스트처럼 **계층별로 테스트를 격리하고, 병렬로 실행하여 개발 생산성을 향상시키려는 의도**가 담겨져 있습니다. 2010년에 작성된 link:https://testing.googleblog.com/2010/12/test-sizes.html[Google Testing Blog - Test Sizes]를 참고했습니다.

현재 유지중인 테스트는 총 90여개로 평균 12~13sec의 시간을 소요합니다. 사이즈 별 전체 테스트 케이스는 _(Large ~ Small) 22%, 32%, 45%_ 비율로 분포되며, 실행 시 소요 시간은 (같은 순서로) _5sec, 3.1sec, 6sec_ 입니다. 

이러한 테스트 격리 환경 + 사이즈별 테스팅을 통해 코드 수정 후 테스트 진행 시, 전체 테스트를 실행시키는 것 대비 **최소 50% 이상(12sec → 6sec)의 소요시간을 감소**시킬 수 있습니다. 

---

- *Token 기반 로그인을 왜 선택하게 됐는지?*

로그인 기능에서 필요한 '상태 보관' 전략에는 `Session based`, `Token based` 두 가지 선택지가 존재했습니다. 두 선택지는 **보안**과 **수평 확장성(horizontal scalability)** 관점에서의 트레이드오프가 존재했습니다. 각 선택지의 로그인 상태 발급 절차는 아래와 같습니다. 

Session based 방식은 서버가 사용자의 로그인 상태를 보관하며 이에 대한 제어권 역시 서버가 갖습니다. 일반적으로 쿠키를 통해 서버에 보관 중인 로그인 상태의 식별 값(Ex. Session ID)을 교환하며 Statuful 하게 로그인 상태를 유지합니다. 

반면 Token based 방식은 클라이언트가 로그인 상태를 인증하기 위한 절차를 통해 서버로부터 토큰을 발행받고 이를 클라이언트가 자체적으로 유지합니다. 정상적인 사용자가 요청을 보내리라 가정하는 상호 신뢰를 기반으로 하죠.

> 보안

위와 같은 특성 때문에 Session based 방식은 상대적으로 *보안* 에 강점을 갖습니다. 서버가 상태 제어권을 갖고 있으므로 의심스러운 행동이 포착되거나, 보안 관련 위협을 인지했을 때 유지 중인 Session ID DB에서 특정 ID를 조회, 삭제하는 행위 등을 통해 곧바로 사용자의 권한을 박탈시킬 수 있습니다. 

반면 Token based 방식은 제어권의 주체가 클라이언트입니다. 토큰이 전송되기 전까진 해당 토큰의 존재 여부마저 서버가 파악할 수 없죠. 따라서 사용자를 일방적으로 로그아웃시키거나, 세부 정보를 변경하는 등의 보안 관련 작업이 불가능합니다. 토큰의 전송 주체가 최초 발급한 사람과 달라져도 이를 알 수 없다는 단점도 존재합니다.

> 수평 확장성(horizontal scalability)

또 다른 점은 `수평 확장성(horizontal scalability)` 입니다. Session based 방식은 Stateful하기 때문에 웹 애플리케이션의 개수가 늘어날 때 상태 유지에 어려움을 겪습니다. 항상 동일한 로그인 상태를 유지하기 위해 우린 모든 서버에서 로그인 프로세스가 완료된 Session Id를 동기화해야 하기 때문이죠.

반면 Token based 방식은 서버에선 발급된 토큰에 대한 유효성 검사만 수행합니다. 이러한 Stateless한 특성 때문에 수평적 확장에 훨씬 수월합니다. 어느 서버로 접속하든 전달받은 토큰이 유효하다는 검증만 진행하면 끝입니다. 

> 결론

위와 같은 고민 끝에 보안의 강점을 일부 포기하더라도, 서비스 규모 확대에 따른 **서버의 수평 확장성을 보장**하기 위해 **`Token based` 방식을 선택**했습니다.


// Metadata:
:description: Spring boot multimodule project with Kotlin language
:keywords: kotlin, spring
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font
